### PR TITLE
Update Hushboard

### PR DESCRIPTION
**Pull request by jbouter**
Modify `__main__.py`:
  - Put main into a function to allow entrypoint via setup.py

Add setup.py
  - Allow for an easy installation

Update README
  - Add installation instructions for manual installation
  - Add installation instructions for Arch

Add MANIFEST.in
  - Describe which sources to include

### CODE REVIEW

**Comment by jbouter** [comment]
Kindly verify you agree with the small `__main__.py` "rewrite", and verify it works with snap packages still :-) Other than that, we have made no modifications on the original codebase.

Having the `setup.py` allows for easy (non-snap) installation. Arch AUR package ready once this has been merged :-) <3

**Comment by jbouter** [comment]
The succesful AUR build based on my fork of the repo can be [viewed here](https://github.com/jbouter/aur-test/runs/1669480324?check_suite_focus=true)

**Comment by stuartlangridge** [comment]
I'm cool with this, and thank you very much! @popey is this ok for the existing snap packaging? There are new files added -- will they end up in the snap? if they do, is that ok? If @popey's happy then I am :)

**Comment by jbouter** [comment]
Perhaps adding the `setup.py` allows for @popey to do a different `snap` install as well (though, dumping the files in there should still work)

**Comment by popey** [comment]
If we use the python plugin with this setup.py it fails because you're asking for python > 3.6.12, Ubuntu 18.04 (core18) has 3.6.9. Is there something in 3.6.12 you're after or can we use => 3.6.9 instead?

**Comment by popey** [comment]
LGTM!

**Pull request merged**
